
# Copyright (c) 2018-2021 Qualcomm Technologies, Inc.

# All rights reserved.

# Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the
# limitations in the disclaimer below) provided that the following conditions are met:

# * Redistributions of source code must retain the above copyright notice, this list of conditions and the following
# disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials provided with the distribution.
# * Neither the name of Qualcomm Technologies, Inc. nor the names of its contributors may be used to endorse or promote
# products derived from this software without specific prior written permission.
# * The origin of this software must not be misrepresented; you must not claim that you wrote the original software.
# If you use this software in a product, an acknowledgment is required by displaying the trademark/log as per the details
# provided here: https://www.qualcomm.com/documents/dirbs-logo-and-brand-guidelines
# * Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.
# * This notice may not be removed or altered from any source distribution.

# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY
# THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.


# DRS global configurations
global:

  # maximum allowed Secondary pairs with one Primary MSISDN
  pair_limit: 4

  # Length of pair-Code
  pc_length: 8

  # No of IMEIs per device
  imeis_per_device: 5

  validation_regex:
    msisdn: '^923[0-9]{9}$'
    paircode: '^[a-zA-Z0-9]{8}$'
    imei: '^[A-F0-9]{14,16}$'
    imsi: '\d{15}'
    mno: '^.{1,50}$'
    start_limit: '\d+'
    serial_no: '^\S{1,100}$'
    mac: '^([0-9A-F]{2,4}[.:-]){3,7}([0-9A-F]{2,4})$'
    rat: '^(2G|3G|4G|5G)[,]?(2G|3G|4G|5G)?[,]?(2G|3G|4G|5G)?[,]?(2G|3G|4G|5G)?$'
    date: '^((19|20)\d{2})\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])$'
    email: '^[a-zA-Z0-9\x2D\x2E\x5F]+@[a-zA-Z0-9_]+?\.[a-zA-Z]{2,3}$'

  # DataBase Parameters
  dbname: 'dps'
  dbusername: 'postgres'
  dbpassword: 'sms003'
  dbhost: '192.168.100.69'

  # SQL_ALCHEMY Parameters
  pool_size: 100
  pool_timeout: 20
  pool_recycle: 10
  overflow_size: 275

  # File extensions allowed for bulk uploads
  allowed_extensions: ['csv', 'txt']

  # Technologies allowed to communicate with Kannel
  allowed_technologies: ['SMS', 'sms', 'USSD', 'ussd']

  # DPS cases to be handled
  dps_cases: [ "first_pair", "additional_pair", "del_single_pair", "del_all_pairs", "sim_change", "verify_pair",
               "find_pair" ]

  # Operators related parameters
  CC: '92'
  MNO_1: 'operator01'
  MNO_2: 'operator02'
  MNO_3: 'operator03'
  MNO_4: 'operator04'
  MNO_5: 'Huawei'
  MNO_6: 'huawei'

  # Mobile Operator Names & Numbers
  num_of_mnos: 6
  MNO_Names: ["operator01", "operator02", "operator03", "operator04", "Huawei", "huawei"]

  # Jasmin related parameters
#  jasmin_sms: 'http://192.168.100.41/sms/'
  dns_sms: 'http://127.0.0.1:8000/sms/'

  # Kannel related parameters
  kannel_sms: 'http://192.168.100.70:13013/cgi-bin/sendsms'
  kannel_username: 'tester'
  kannel_password: 'foobar'
  kannel_smsc: 'at'
  kannel_shortcode: '03029847788'

  # Pair-List generation Path
  pairlist_path: '/home/munawar/PycharmProjects/DPS-v2.0/Device-Pairing-Subsystem/pairing_lists'

  # System Paths for files
  Download_Path: '/home/munawar/PycharmProjects/DPS-v2.0/Device-Pairing-Subsystem/downloads'
  Upload_Path: '/home/munawar/PycharmProjects/DPS-v2.0/Device-Pairing-Subsystem/uploads'

  # path for test-documents
  test_doc_path: '/home/munawar/PycharmProjects/DPS-v2.0/Device-Pairing-Subsystem//tests/unittest_data/sample_files/'

  # SMS Texts
  # Additional-Pair Messages
  sms_pair_limit_breached: 'Pairing limit breached: need to remove any existing pair'

  # Multi-Language Support
  supported_languages:
    languages: ['es', 'id', 'en']
    default_language: 'en'

  regex:
    id:
      username: '^(?! )[A-Za-z\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s\x23\x2D\x40\x5F]{1,1000}(?<! )$'
      case_comment: '^(?! )[\x21-\x7E\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s]{1,1000}(?<! )$'
      full_name: '^(?! )[A-Za-z\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s]{1,1000}(?<! )$'
      address: '^(?! )[A-Za-z0-9\x23\x2F\x2D\x40\x5F\x5C\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s]{1,1000}(?<! )$'
      brand: '^(?! )[A-Za-z0-9\x2D\x26\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s]{1,1000}(?<! )$'
      model_name: '^(?! )[A-Za-z0-9\x27\x2D\x28\x29\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s]{1,1000}(?<! )$'
      description: '^(?! )[\x21-\x7E\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s]{1,1000}(?<! )$'
    es:
      username: '^(?! )[A-Za-z\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s\x23\x2D\x40\x5F]{1,1000}(?<! )$'
      case_comment: '^(?! )[\x21-\x7E\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s]{1,1000}(?<! )$'
      full_name: '^(?! )[A-Za-z\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s]{1,1000}(?<! )$'
      address: '^(?! )[A-Za-z0-9\x23\x2F\x2D\x40\x5F\x5C\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s]{1,1000}(?<! )$'
      brand: '^(?! )[A-Za-z0-9\x2D\x26\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s]{1,1000}(?<! )$'
      model_name: '^(?! )[A-Za-z0-9\x27\x2D\x28\x29\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s]{1,1000}(?<! )$'
      description: '^(?! )[\x21-\x7E\xAA\xBA\xC0-\xD6\xD8-\xF6\xF8-\u02B8\u02E0-\u02E4\u1D00-\u1D25\u1D2C-\u1D5C\u1D62-\u1D65\u1D6B-\u1D77\u1D79-\u1DBE\u1E00-\u1EFF\u2071\u207F\u2090-\u209C\u212A\u212B\u2132\u214E\u2160-\u2188\u2C60-\u2C7F\uA722-\uA787\uA78B-\uA78E\uA790-\uA7AD\uA7B0\uA7B1\uA7F7-\uA7FF\uAB30-\uAB5A\uAB5C-\uAB5F\uAB64\uFB00-\uFB06\uFF21-\uFF3A\uFF41-\uFF5A\s]{1,1000}(?<! )$'
    en:
      username: '^(?! )[A-Za-z\s\x23\x2D\x40\x5F]{1,1000}(?<! )$'
      case_comment: '^(?! )[\x21-\x7E\s]{1,1000}(?<! )$'
      full_name: '^(?! )[A-Za-z\s]{1,1000}(?<! )$'
      address: '^(?! )[A-Za-z0-9\x23\x2F\x2D\x40\x5F\x5C\s]{1,1000}(?<! )$'
      brand: '^(?! )[A-Za-z0-9\x2D\x26\s]{1,100}(?<! )$'
      model_name: '^(?! )[A-Za-z0-9\x27\x2D\x28\x29\s]{1,100}(?<! )$'
      description: '^(?! )[\x21-\x7E\s]{1,1000}(?<! )$'
